spring.application.name=comunicacion-service
server.port=8093

spring.datasource.url=jdbc:mysql://mysql-db:3306/colegio_comunicacion?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true